GestioneRimborsi.Web/Controllers/SecurityController.cs
using GruppoCap.Core.Mvc;
using GruppoCap.Security.PEM;

namespace GestioneRimborsi.Web.Controllers
{
    public class SecurityController : BaseSecurityController
    {
        // CTOR
        public SecurityController(IPEMService pemService)
            : base(pemService)
        {
            // EMPTY BY DEFAULT
        }
    }
}

GestioneRimborsi.Web/Views/Security/PermissionGroupDetail.cshtml
@using GruppoCap
@using GruppoCap.Core.Data
@using GruppoCap.Authentication.Core

@model IPermissionGroup
@{
    ViewBag.Title = Model.Title;

    IUser _currentUser = RevoRequest.CurrentUser;
}

<div class="row">

    <div class="col-sm-2">
        <div class="row">
            <div class="col-sm-12">
                <ul class="nav nav-pills nav-stacked detail-menu">
                    @Html.AreaMenuLink("Permissions", "fa-cube", CommonUrls.Permissions)
                    @Html.AreaMenuLink("Permission Groups", "fa-cubes", CommonUrls.PermissionGroups, true)
                </ul>
            </div>
        </div>
    </div>

    <div class="col-sm-10">

        <div class="row grid-title">
            <div class="col-sm-12">
                <h1>
                    <i class="fa fa-lg fa-cubes"></i> @ViewBag.Title
                </h1>
            </div>
        </div>

        <div class="row">

            <div class="col-sm-12">

                <form role="form" class="breath-on-top-20">

                    <div class="row">
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label for="txtApplicationId" class="control-label">Permission Group Id</label>
                                <input type="text" class="form-control" id="txtPermissionGroupId" value="@Model.PermissionGroupId" disabled>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label for="txtTitle" class="control-label">Title</label>
                                <input type="text" class="form-control input-lg" id="txtTitle" placeholder="Insert title" maxlength="50" value="@Model.Title">
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label for="txtDescription" class="control-label">Description</label>
                                <textarea type="text" class="form-control" id="txtDescription" placeholder="Insert description" maxlength="500" >@Model.Description</textarea>
                            </div>
                        </div>
                    </div>

                    <div class="well" style="margin-top: 20px;">
                        <div class="row">
                            <div class="col-sm-12">
                                <h3 class="well-title"><i class="fa fa-user-secret"></i><span class="text-after-icon">Privilege</span></h3>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-3">
                                <div class="form-group" style="margin-bottom: 0px;">
                                    <label class="control-label">Privileged permission group</label>
                                    @{
                                        String _isPrivilegedDescription, _isPrivilegedClass;
                                        String _groupPrivilegedText = "PRIVILEGED group";
                                        String _groupNotPrivilegedText = "NOT privileged group";

                                        _isPrivilegedDescription = @Model.IsPrivileged ? _groupPrivilegedText : _groupNotPrivilegedText;
                                        _isPrivilegedClass = @Model.IsPrivileged ? "text-primary" : "text-danger";
                                    }

                                    @Html.FontAwesomeCheckbox(
                                        "chkIsPrivileged",
                                        Model.IsPrivileged,
                                        _groupPrivilegedText,
                                        _groupNotPrivilegedText,
                                        "text-primary",
                                        "text-danger",
                                        _isPrivilegedClass,
                                        _isPrivilegedDescription
                                    )
                                </div>
                            </div>
                        </div>

                    </div>

                    <div class="row">
                        <div class="col-sm-12">
                            @Html.Partial("~/Views/Security/_groupPermissions.cshtml", Model)
                        </div>
                    </div>

                    <div class="row breath-on-top-32">
                        <div class="col-sm-12 text-right">
                            <a class="btn btn-lg btn-default" href="@CommonUrls.PermissionGroups">
                                <i class="fa fa-lg fa-arrow-circle-o-left"></i><span class="text-after-icon">Back to Permission Group list</span>
                            </a>
                            <a class="btn btn-lg btn-primary" href="javascript:void(0);" onclick="savePermissionGroup('@Model.PermissionGroupId');">
                                <i id="iconSave" class="fa fa-lg fa-save"></i><span class="text-after-icon">Save</span>
                            </a>
                        </div>
                    </div>

                    

                </form>

            </div>

        </div>

    </div>

</div>

@section scripts {
<script>
    $(function () {
        // INIT BOOTSTRAP TOOLTIP
        $('[data-toggle="tooltip"]').tooltip();
    });

    function savePermissionGroup(permissionGroupId) {
        var _url;
        var _id, _title, _description, _isPrivileged;
        
        startSaveOperation('iconSave');

        _url = '@Url.Action("UpdatePermissionGroup", "Security")';
        _id = permissionGroupId;
        
        _title = $("#txtTitle").val();
        _description = $("#txtDescription").val();
        _isPrivileged = isFontAwesomeChecked('#chkIsPrivileged');
        
        $.ajax({
            url: _url,
            type: 'POST',
            contentType: "application/json; charset=utf-8",
            data: JSON.stringify({
                permissionGroupId: _id,
                title: _title,
                description: _description,
                isPrivileged: _isPrivileged
            }),
            success: function (result) {
                var _resultStatus = result.status;
                if (_resultStatus == 'success') {
                    notifySuccess(result.data.message);
                }
                else {
                    notifyError(result.data.message);
                }
            },
            error: function (request, status, error) {
                notifyError('Something gone wrong saving the data');
            }
        }).done(function () {
            endSaveOperation('iconSave');
        }); // end ajax call
    } // saveUser
</script>
}

GestioneRimborsi.Web/Views/Security/PermissionGroupList.cshtml
@using GruppoCap
@using GruppoCap.Core.Data
@using GruppoCap.Authentication.Core
@using GruppoCap.Security.PEM

@model IList<IPermissionGroup>

@{
    ViewBag.Title = "Permission Groups list";
}

<div class="row">

    <div class="col-sm-2">
        <div class="row">
            <div class="col-sm-12">
                <ul class="nav nav-pills nav-stacked detail-menu">
                    @Html.AreaMenuLink("Permissions", "fa-cube", CommonUrls.Permissions)
                    @Html.AreaMenuLink("Permission Groups", "fa-cubes", CommonUrls.PermissionGroups, true)
                </ul>
            </div>
        </div>
    </div>

    <div class="col-sm-10">

        <div class="row grid-title">
            <div class="col-sm-6">
                <h1>
                    <i class="fa fa-cubes"></i> Permission Groups List
                </h1>
            </div>
            <div class="col-sm-6 text-right" >
                <button type="button" class="btn btn-default title-bar-entity-button" data-toggle="modal" data-target="#createPermissionGroupModal">
                    <i class="fa fa-lg fa-cubes"></i>
                    <span class="text-after-icon">New Permission Group</span>
                </button>
            </div>
        </div>

        <div class="row">

            <div class="col-sm-12 breath-on-top-32" id="permissionGroupTableContainer" style="display: block;">

                @if(Model.Count > 0)
                {
                    @Html.Partial("_permissionGroupList", Model)
                }
                else
                {
                    <div class="alert alert-info" role="alert" style="padding-top: 24px;">
                        <h4><strong><i class="fa fa-lg fa-frown-o"></i></strong><span class="text-after-icon"><strong>No groups here!</strong> It looks like nobody needs them...</span></h4>
                    </div>
                }               

            </div>

        </div>
        
    </div>

    @Html.Partial("_createPermissionGroup")

</div>

@section scripts {
<script>

    $(function () {
        // INIT BOOTSTRAP TOOLTIP
        $('[data-toggle="tooltip"]').tooltip();
    });

</script>
}

GestioneRimborsi.Web/Views/Security/PermissionList.cshtml
@using GruppoCap
@using GruppoCap.Core.Data
@using GruppoCap.Authentication.Core
@using GruppoCap.Security.PEM

@model IList<IPermission>

@{
    ViewBag.Title = "Permissions list";
}

<div class="row">

    <div class="col-sm-2">
        <div class="row">
            <div class="col-sm-12">
                <ul class="nav nav-pills nav-stacked detail-menu">
                    @Html.AreaMenuLink("Permissions", "fa-cube", CommonUrls.Permissions, true)
                    @Html.AreaMenuLink("Permission Groups", "fa-cubes", CommonUrls.PermissionGroups)
                </ul>
            </div>
        </div>
    </div>

    <div class="col-sm-10">

        <div class="row grid-title">
            <div class="col-sm-6">
                <h1>
                    <i class="fa fa-cube"></i> Permission List
                </h1>
            </div>
            <div class="col-sm-6 text-right">
                <button type="button" class="btn btn-default title-bar-entity-button" data-toggle="modal" data-target="#createPermissionModal" onclick="notAvailableFunction();">
                    <i class="fa fa-lg fa-cube"></i>
                    <span class="text-after-icon">New Permission</span>
                </button>
            </div>
        </div>

        <div class="row">

            <div class="col-sm-12" id="permissionTableContainer" style="display: block;">

                @if (Model.Count > 0)
                {
                    @Html.Partial("_permissionList", Model)
                }
                else
                {
                    <div class="alert alert-warning" role="alert" style="padding-top: 24px;">
                        <h4><strong><i class="fa fa-lg fa-frown-o"></i></strong><span class="text-after-icon"><strong>No permission here!</strong> This could be a problem...</span></h4>
                    </div>
                }       

            </div>

        </div>

    </div>

    @*@Html.Partial("_createPermission")*@

</div>

@section scripts {
    <script>

        $(function () {
            // INIT BOOTSTRAP TOOLTIP
            $('[data-toggle="tooltip"]').tooltip();
        });

        function notAvailableFunction() {
            notifyInfo("Funzionalità non disponibile! Ti chiediamo di avere ancora un po' di pazienza...")
        }

    </script>
}

GestioneRimborsi.Web/Views/Security/_createPermissionGroup.cshtml
@using GruppoCap
@using GruppoCap.Core.Data
@using GruppoCap.Authentication.Core

<div class="modal fade" id="createPermissionGroupModal" tabindex="-1" role="dialog" aria-labelledby="createPermissionGroupModalTitle" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="createPermissionGroupModalTitle">
                    <i class="fa fa-lg fa-cubes"></i>
                    <span class="text-after-icon">New Permission Group</span>
                </h4>
            </div>
            <div class="modal-body">
                
                <div class="row">

                    <div class="col-sm-12">

                        <form role="form" class="breath-on-top-8">

                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label for="txtTitle" class="control-label">Title</label>
                                        <input type="text" class="form-control input-lg" id="txtTitle" placeholder="insert title" maxlength="50">
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label for="txtDescription" class="control-label">Description</label>
                                        <textarea class="form-control" id="txtDescription" placeholder="insert description" maxlength="500" ></textarea>
                                    </div>
                                </div>
                            </div>

                        </form>

                    </div>

                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-lg btn-default" data-dismiss="modal">
                    <i class="fa fa-lg fa-arrow-circle-o-left"></i><span class="text-after-icon">Annulla</span>
                </button>
                <a class="btn btn-lg btn-primary" href="javascript:void(0);" onclick="createPermissionGroup();">
                    <i id="iconSave" class="fa fa-lg fa-save"></i><span class="text-after-icon">Salva</span>
                </a>
            </div>
        </div>
    </div>
</div>

<script>
    $(function () {
        
    });

    function createPermissionGroup() {

        var _url;
        var _title, _description;

        startSaveOperation('iconSave');

        _url = '@Url.Action("CreatePermissionGroup", "Security")';

        _title = $("#txtTitle").val();
        _description = $("#txtDescription").val();
        
        $.ajax({
            url: _url,
            type: 'POST',
            contentType: "application/json; charset=utf-8",
            data: JSON.stringify({
                title: _title,
                description: _description
            }),
            success: function (result) {
                var _resultStatus = result.status;
                if (_resultStatus == 'success') {
                    notifySuccess(result.data.message);
                }
                else {
                    notifyError(result.data.message);
                }
            },
            error: function (request, status, error) {
                notifyError('Something gone wrong trying to save the datas...');
            }
        }).done(function () {
            endSaveOperation('iconSave');
            $('#createPermissionGroupModal').modal('hide');
        }); // end ajax call
    } // saveUser
</script>

GestioneRimborsi.Web/Views/Security/_groupPermissions.cshtml
@using GruppoCap
@using GruppoCap.Core.Data
@using GruppoCap.Core.Permission
@using GruppoCap.Authentication.Core
@using GruppoCap.Security.PEM

@model IPermissionGroup

@{
    IPermissionManager PEM = RevoContext.PermissionManager;
    
    IList<IPermission> _permissions;
    _permissions = PEM.BrowsePermissions(RevoRequest.CurrentUser.IsPrivileged);

    Boolean? _directGrant;
    Boolean? _inheritedGrant;

    String _grantIcon, _deleteIconShow;
}

<div class="row">
    <div class="col-sm-12">
    @{
        String _lastCategoryName = String.Empty;
        foreach (IPermission _p in _permissions)
        {
            if (_p.CategoryName != _lastCategoryName)
            {
                <h4 class="permission-category">@_p.CategoryName</h4>
            }

            <div class="row permission-row">
                <div class="col-sm-2 permission-code">@_p.PermissionCode</div>
                <div class="col-sm-8 permission-description">@_p.Description</div>
                @{
                    _directGrant = PEM.GetGroupGrantDirect(_p.PermissionCode, Model.PermissionGroupId);
                    _inheritedGrant = PEM.GetGroupGrantWithFallback(_p.PermissionCode, Model.PermissionGroupId);

                    if(_directGrant.HasValue)
                    {
                        _grantIcon = _directGrant.Value ? CommonSnippets.AllowedGrant : CommonSnippets.DeniedGrant;
                        <div class="col-sm-1 text-right">
                            <a id="a_change_@_p.PermissionId" href="javascript:void(0);" onclick="changeDirectGrant('@_p.PermissionCode', '@Model.PermissionGroupId');">
                                @_grantIcon.ToRaw()
                            </a>
                        </div>
                    
                        _deleteIconShow = String.Empty;
                    }
                    else
                    {
                        _grantIcon = _inheritedGrant.Value ? CommonSnippets.InheritedAllowedGrant : CommonSnippets.InheritedDeniedGrant;
                        <div class="col-sm-1 text-right">
                            <a id="a_change_@_p.PermissionId" href="javascript:void(0);" onclick="changeDirectGrant('@_p.PermissionCode', '@Model.PermissionGroupId');">
                                @_grantIcon.ToRaw()
                            </a>
                        </div>

                        _deleteIconShow = "display: none;";
                    }

                    <div class="col-sm-1 text-left" style="padding-top: 8px;">
                        <span class="text-after-icon" id="a_delete_@_p.PermissionId" style="@_deleteIconShow">
                            <a href="javascript:void(0);" onclick="deleteDirectGrant('@_p.PermissionCode', '@Model.PermissionGroupId');">
                                <i class="fa fa-lg fa-fw fa-trash"></i>
                            </a>
                        </span>

                    </div>
                }

            </div>

            _lastCategoryName = _p.CategoryName;

        }
    }
    </div>
</div>


<script>
    function changeDirectGrant(permissionCode, permissionGroupId) {
        var _url = "@CommonUrls.PermissionSetGroupGrant("_permissionCode_", "_permissionGroupId_")".replace('_permissionCode_', permissionCode).replace('_permissionGroupId_', permissionGroupId);

        $.ajax({
            url: _url,
            type: 'POST',
            contentType: "application/json; charset=utf-8",
            data: JSON.stringify({
                permissionCode: permissionCode,
                permissionGroupId: permissionGroupId
            }),
            success: function (result) {
                var _resultStatus = result.status;
                if (_resultStatus == 'success') {
                    notifySuccess(result.data.message);
                    $('#a_change_' + result.data.permissionId).html('' + result.data.htmlGrant + '');
                    $('#a_delete_' + result.data.permissionId).show();
                }
                else {
                    notifyError(result.data.message);
                }
            },
            error: function (request, status, error) {
                notifyError('Qualcosa è andato storto durante il salvataggio dei dati');
            }
        }).done(function () {

        }); // end ajax call
    }

    function deleteDirectGrant(permissionCode, permissionGroupId) {
        var _url = "@CommonUrls.PermissionRemoveUserGrant("_permissionCode_", "_permissionGroupId_")".replace('_permissionCode_', permissionCode).replace('_permissionGroupId_', permissionGroupId);

        $.ajax({
            url: _url,
            type: 'POST',
            contentType: "application/json; charset=utf-8",
            data: JSON.stringify({
                permissionCode: permissionCode,
                permissionGroupId: permissionGroupId
            }),
            success: function (result) {
                var _resultStatus = result.status;
                if (_resultStatus == 'success') {
                    notifySuccess(result.data.message);
                    $('#a_change_' + result.data.permissionId).html('' + result.data.htmlGrant + '');
                    $('#a_delete_' + result.data.permissionId).hide();
                }
                else {
                    notifyError(result.data.message);
                }
            },
            error: function (request, status, error) {
                notifyError('Qualcosa è andato storto durante il salvataggio dei dati');
            }
        }).done(function () {

        }); // end ajax call
    }

</script>

GestioneRimborsi.Web/Views/Security/_permissionGroupList.cshtml
@using GruppoCap
@using GruppoCap.Core.Data
@using GruppoCap.Authentication.Core

@model IList<IPermissionGroup>

<table id="gridPermissionGroups" class="table table-condensed table-hover">
    <thead>
        <tr>
            <th width="3%"></th>
            <th>Nome</th>
            <th>Descrizione</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @{
            foreach (IPermissionGroup _pg in Model)
            {
                String _trIcon = String.Empty;

                if (_pg.IsPrivileged)
                {
                    _trIcon += CommonSnippets.IsPrivileged;
                }

                <tr onclick="loadPermissionGroupDetail('@_pg.PermissionGroupId');" >
                    <td>@Html.Raw(_trIcon)</td>
                    <td>@_pg.Title</td>
                    <td>@_pg.Description</td>
                    <td>
                        @*<a class="deleteButtonInList" href="javascript:void(0);" onclick="loadPermissiongGroupDeletePreview('@_pg.PermissionGroupId');"><i class="fa fa-lg fa-fw fa-trash"></i></a>*@
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

<script>
    $('.deleteButtonInList').click(function (event) {
        event.stopPropagation();
    });

    function loadPermissionGroupDetail(permissionGroupId) {
        var _url = "@CommonUrls.PermissionGroupDetail("_permissionGroupId_")".replace('_permissionGroupId_', permissionGroupId);
        window.location.href = _url;
    }
</script>

GestioneRimborsi.Web/Views/Security/_permissionList.cshtml
@using GruppoCap
@using GruppoCap.Core.Data
@using GruppoCap.Authentication.Core
@using GruppoCap.Security.PEM


@model IList<IPermission>

<div class="row">
    <div class="col-sm-12">

        @{
            String _lastCategoryName = String.Empty;
            foreach (IPermission _p in Model)
            {
                String _grantIcon;
                _grantIcon = _p.DefaultGrant ? CommonSnippets.AllowedGrant : CommonSnippets.DeniedGrant;

                if (_p.CategoryName != _lastCategoryName)
                {
                    <h4 class="permission-category">@_p.CategoryName</h4>
                }

                <div class="row permission-row">
                    <div class="col-sm-3 permission-code">@_p.PermissionCode</div>
                    <div class="col-sm-8 permission-description">@_p.Description</div>
                    <div class="col-sm-1">
                        <a id="a_@_p.PermissionId" href="javascript:void(0);" onclick="changeDefaultGrant('@_p.PermissionCode');">
                            @_grantIcon.ToRaw()
                        </a>
                    </div>
                </div>

                _lastCategoryName = _p.CategoryName;

            }
        }

    </div>
</div>

<script>
    function changeDefaultGrant(permissionCode) {
        var _url = "@CommonUrls.PermissionSetDefaultGrant("_permissionCode_")".replace('_permissionCode_', permissionCode);

        $.ajax({
            url: _url,
            type: 'POST',
            contentType: "application/json; charset=utf-8",
            data: JSON.stringify({
                permissionCode: permissionCode
            }),
            success: function (result) {
                var _resultStatus = result.status;
                if (_resultStatus == 'success') {
                    notifySuccess(result.data.message);
                    $('#a_' + result.data.permissionId).html('' + result.data.htmlGrant + '');
                }
                else {
                    notifyError(result.data.message);
                }
            },
            error: function (request, status, error) {
                notifyError('Qualcosa è andato storto durante il salvataggio dei dati');
            }
        }).done(function () {

        }); // end ajax call

    }
</script>

GestioneRimborsi.Web/Views/Security/_userPermissions.cshtml
@using GruppoCap
@using GruppoCap.Core.Data
@using GruppoCap.Core.Permission
@using GruppoCap.Authentication.Core
@using GruppoCap.Security.PEM

@model User

@{
    IPermissionManager PEM = RevoContext.PermissionManager;
    
    IList<IPermission> _permissions;
    _permissions = PEM.BrowsePermissions(RevoRequest.CurrentUser.IsPrivileged);

    Boolean? _directGrant;
    Boolean? _inheritedGrant;

    String _grantIcon, _deleteIconShow;
}

<div class="row">
    <div class="col-sm-12">
    @{
        String _lastCategoryName = String.Empty;
        foreach (IPermission _p in _permissions)
        {
            if (_p.CategoryName != _lastCategoryName)
            {
                <h4 class="permission-category">@_p.CategoryName</h4>
            }

            <div class="row permission-row">
                <div class="col-sm-2 permission-code">@_p.PermissionCode</div>
                <div class="col-sm-8 permission-description">@_p.Description</div>
                @{
                    _directGrant = PEM.GetUserGrantDirect(_p.PermissionCode, Model.UserId);
                    _inheritedGrant = PEM.GetUserGrantWithFallback(_p.PermissionCode, Model.UserId);

                    if(_directGrant.HasValue)
                    {
                        _grantIcon = _directGrant.Value ? CommonSnippets.AllowedGrant : CommonSnippets.DeniedGrant;
                        <div class="col-sm-1 text-right">
                            <a id="a_change_@_p.PermissionId" href="javascript:void(0);" onclick="changeDirectGrant('@_p.PermissionCode', '@Model.UserId');">
                                @_grantIcon.ToRaw()
                            </a>
                        </div>
                    
                        _deleteIconShow = String.Empty;
                    }
                    else
                    {
                        _grantIcon = _inheritedGrant.Value ? CommonSnippets.InheritedAllowedGrant : CommonSnippets.InheritedDeniedGrant;
                        <div class="col-sm-1 text-right">
                            <a id="a_change_@_p.PermissionId" href="javascript:void(0);" onclick="changeDirectGrant('@_p.PermissionCode', '@Model.UserId');">
                                @_grantIcon.ToRaw()
                            </a>
                        </div>

                        _deleteIconShow = "display: none;";
                    }

                    <div class="col-sm-1 text-left" style="padding-top: 8px;">
                        <span class="text-after-icon" id="a_delete_@_p.PermissionId" style="@_deleteIconShow">
                            <a href="javascript:void(0);" onclick="deleteDirectGrant('@_p.PermissionCode', '@Model.UserId');">
                                <i class="fa fa-lg fa-fw fa-trash"></i>
                            </a>
                        </span>

                    </div>
                }

            </div>

            _lastCategoryName = _p.CategoryName;

        }
    }
    </div>
</div>


<script>
    function changeDirectGrant(permissionCode, userId) {
        var _url = "@CommonUrls.PermissionSetUserGrant("_permissionCode_", "_userId_")".replace('_permissionCode_', permissionCode).replace('_userId_', userId);

        $.ajax({
            url: _url,
            type: 'POST',
            contentType: "application/json; charset=utf-8",
            data: JSON.stringify({
                permissionCode: permissionCode,
                userId: userId
            }),
            success: function (result) {
                var _resultStatus = result.status;
                if (_resultStatus == 'success') {
                    notifySuccess(result.data.message);
                    $('#a_change_' + result.data.permissionId).html('' + result.data.htmlGrant + '');
                    $('#a_delete_' + result.data.permissionId).show();
                }
                else {
                    notifyError(result.data.message);
                }
            },
            error: function (request, status, error) {
                notifyError('Qualcosa è andato storto durante il salvataggio dei dati');
            }
        }).done(function () {

        }); // end ajax call
    }

    function deleteDirectGrant(permissionCode, userId) {
        var _url = "@CommonUrls.PermissionRemoveUserGrant("_permissionCode_", "_userId_")".replace('_permissionCode_', permissionCode).replace('_userId_', userId);

        $.ajax({
            url: _url,
            type: 'POST',
            contentType: "application/json; charset=utf-8",
            data: JSON.stringify({
                permissionCode: permissionCode,
                userId: userId
            }),
            success: function (result) {
                var _resultStatus = result.status;
                if (_resultStatus == 'success') {
                    notifySuccess(result.data.message);
                    $('#a_change_' + result.data.permissionId).html('' + result.data.htmlGrant + '');
                    $('#a_delete_' + result.data.permissionId).hide();
                }
                else {
                    notifyError(result.data.message);
                }
            },
            error: function (request, status, error) {
                notifyError('Qualcosa è andato storto durante il salvataggio dei dati');
            }
        }).done(function () {

        }); // end ajax call
    }

</script>