GestioneRimborsi.Web/Controllers/GestioneDisposizioniController.cs
using GruppoCap.Core;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using GruppoCap.Core.Data;
using GestioneRimborsi.Core;
using GruppoCap;
using System.Xml;
using System.Text;
using System.IO;
using SepaManager.Base;
using System.Xml.Linq;
using System.Net.Mail;
using GruppoCap.Mail;

namespace GestioneRimborsi.Web.Controllers
{
    public class GestioneDisposizioniController : RevoController
    {

        private ILottoRimborsiService _lottorimborsiService = null;
        // CTOR
        public GestioneDisposizioniController(ILottoRimborsiService lottorimborsiService)
        {
            _lottorimborsiService = lottorimborsiService;
        }

        public ActionResult List()
        {
            return View(_lottorimborsiService.SepaUsers());
        }

        public ActionResult InnerList(string UserName)
        {
            try
            {
                if (string.IsNullOrEmpty(UserName))
                    return PartialMessage(HtmlSnippets.Alert.Info("Nessun risultato da mostrare..."));

                ISubCollection<SepaHeader> _elencoDisposizioni = _lottorimborsiService.GetSepaHeaderByUser(UserName);


                if (_elencoDisposizioni.Items.HasValues() == false)
                {
                    return PartialMessage(
                        HtmlSnippets.Alert.Warning(string.Format("Non ho trovato risultati per l'utente {0}", UserName))
                    );
                }
                ViewData.Add("UserName", UserName);
                return PartialView("~/Views/GestioneDisposizioni/_elencoDisposizioni.cshtml", _elencoDisposizioni);
            }
            catch (Exception ex)
            {
                if (RevoContext.IdentityManager.CurrentUser.IsPrivileged)
                    return PartialMessage(HtmlSnippets.Alert.Error(string.Format("Errore durante la lettura delle disposizioni...{0}{1}", Environment.NewLine, ex)));
                else
                    return PartialMessage(HtmlSnippets.Alert.Error("Errore durante la lettura delle disposizioni..."));
            }
        }

        public FileResult DownloadFileDisposizioni(long id)
        {
            var proxy = new BankXMLManager.BankXMLServiceClient();

            if (id <= 0)
                throw new ApplicationException("Errore durante la creazione del file xml...");


            //   BankXMLOutput _XmlOutput = proxy.GetXmlDocument(id, true);            
            BankXMLOutput _XmlOutput = proxy.RegenerateXmlDocument(id);

            System.Xml.Linq.XElement _xmlFile = XElement.Parse(_XmlOutput.XmlDocument.OuterXml);
            //StringBuilder fs = new StringBuilder();
            StringWriterWithEncoding fs = new StringWriterWithEncoding(Encoding.UTF8);

            using (XmlWriter xmlW = XmlWriter.Create(fs, new XmlWriterSettings() { OmitXmlDeclaration = false, ConformanceLevel = ConformanceLevel.Document, Encoding = Encoding.UTF8 }))
            {
                _xmlFile.WriteTo(xmlW);
                xmlW.Flush();
            }
            Console.WriteLine("Task Executed");
            byte[] bytes = Encoding.UTF8.GetBytes(fs.ToString());
            HttpContext.Response.Headers.Add("Content-Disposition", string.Format("attachment; filename=\"{0}\"", (_XmlOutput.FileName ?? string.Format("{0}_{1}", id, DateTime.Now.ToString("yyyyMMddHHmmssms"))).EnsureEndsWith(".xml")));

            return File(bytes, "text/xml");
        }

        public FileResult DownloadCsvDisposizioni(long id)
        {
            var proxy = new BankXMLManager.BankXMLServiceClient();

            if (id <= 0)
                throw new ApplicationException("Errore durante la creazione del file csv...");

            List<String> _CsvOutput = proxy.CreateCsvDocument(id);            
            string csv = String.Empty;

            foreach (var item in _CsvOutput)
            {
                csv += item + ";";
                csv += Environment.NewLine;
            }

            return File(new System.Text.UTF8Encoding().GetBytes(csv), "text/csv", "CsvDoc_n" + id.ToString() + ".csv");
        }

        [Authorize]
        public ActionResult SearchSepaHeader()
        {
            try
            {
                ISubCollection<SepaHeader> _elencoDisposizioni = _lottorimborsiService.GetSepaHeader();
                return PartialView("~/Views/GestioneDisposizioni/_elencoDisposizioni.cshtml", _elencoDisposizioni);
            }
            catch (Exception ex)
            {
                if (RevoContext.IdentityManager.CurrentUser.IsPrivileged)
                    return PartialMessage(HtmlSnippets.Alert.Error(string.Format("Errore durante la ricerca...{0}{1}", Environment.NewLine, ex)));
                else
                    return PartialMessage(HtmlSnippets.Alert.Error("Errore durante la ricerca..."));
            }
        }

        [Authorize]
        public ActionResult SearchSepaCreditTransaction(long id)
        {
            try
            {
                ISubCollection<SepaCreditTransaction> _elencoTransazioni = _lottorimborsiService.GetSepaCreditTransaction(id);
                var count = 0;
                foreach(var item in _elencoTransazioni.Items)
                {
                    count++;
                    if (item.CdtrpStladrTownName == "LONATE POZZOLO   VA")
                    {
                        string comune = item.CdtrpStladrTownName;
                        string provincia = item.CdtrpStladrProvince;
                    }
                }
                return PartialView("~/Views/GestioneDisposizioni/_elencoTransazioni.cshtml", _elencoTransazioni);
            }
            catch (Exception ex)
            {
                if (RevoContext.IdentityManager.CurrentUser.IsPrivileged)
                    return PartialMessage(HtmlSnippets.Alert.Error(string.Format("Errore durante la ricerca...{0}{1}", Environment.NewLine, ex)));
                else
                    return PartialMessage(HtmlSnippets.Alert.Error("Errore durante la ricerca..."));
            }
        }


        [Authorize]
        public ActionResult DeleteSepaCreditTransaction(long id)
        {
            try
            {
                ISubCollection<SepaCreditTransaction> _elencoTransazioni = _lottorimborsiService.DeleteSepaCreditTransaction(id, RevoRequest.CurrentUser.UserId);
                return PartialView("~/Views/GestioneDisposizioni/_elencoTransazioni.cshtml", _elencoTransazioni);
            }
            catch (Exception ex)
            {
                if (RevoContext.IdentityManager.CurrentUser.IsPrivileged)
                    return PartialMessage(HtmlSnippets.Alert.Error(string.Format("Errore durante la ricerca...{0}{1}", Environment.NewLine, ex)));
                else
                    return PartialMessage(HtmlSnippets.Alert.Error("Errore durante la ricerca..."));
            }
        }

        [Authorize]
        public ActionResult RecuperaSepaCreditTransaction(long id)
        {
            try
            {
                ISubCollection<SepaCreditTransaction> _elencoTransazioni = _lottorimborsiService.RecuperaSepaCreditTransaction(id, RevoRequest.CurrentUser.UserId);
                return PartialView("~/Views/GestioneDisposizioni/_elencoTransazioni.cshtml", _elencoTransazioni);
            }
            catch (Exception ex)
            {
                if (RevoContext.IdentityManager.CurrentUser.IsPrivileged)
                    return PartialMessage(HtmlSnippets.Alert.Error(string.Format("Errore durante la ricerca...{0}{1}", Environment.NewLine, ex)));
                else
                    return PartialMessage(HtmlSnippets.Alert.Error("Errore durante la ricerca..."));
            }
        }

        [Authorize]
        public ActionResult SchedaModifiche(long id)
        {
            try
            {
                SepaCreditTransaction _transazione = _lottorimborsiService.GetTransactionByID(id);
                return PartialView("~/Views/GestioneDisposizioni/_schedaModifiche.cshtml", _transazione);
            }
            catch (Exception ex)
            {
                if (RevoContext.IdentityManager.CurrentUser.IsPrivileged)
                    return PartialMessage(HtmlSnippets.Alert.Error(string.Format("Errore durante la ricerca ...{0}{1}", Environment.NewLine, ex)));
                else
                    return PartialMessage(HtmlSnippets.Alert.Error("Errore durante la ricerca..."));
            }
        }

        [Authorize]
        public ActionResult SchedaElencoModifiche(long id)
        {
            try
            {
                return PartialView("~/Views/GestioneDisposizioni/_schedaElencoModifiche.cshtml", id);
            }
            catch (Exception ex)
            {
                if (RevoContext.IdentityManager.CurrentUser.IsPrivileged)
                    return PartialMessage(HtmlSnippets.Alert.Error(string.Format("Errore durante la ricerca ...{0}{1}", Environment.NewLine, ex)));
                else
                    return PartialMessage(HtmlSnippets.Alert.Error("Errore durante la ricerca..."));
            }
        }

        [Authorize]
        public ActionResult ModificaDisposizioni(long id, String nuovoIban, String nuovoBeneficiario, String motivazione)
        {
            try
            {

                SepaCreditTransaction _VecchiaTransazione = _lottorimborsiService.GetTransactionByID(id);
                ISubCollection <SepaCreditTransaction> _transazioni = _lottorimborsiService.ModificaTransazione(id, nuovoIban, nuovoBeneficiario, motivazione, RevoRequest.CurrentUser.UserId);

                if (_transazioni.Items.Any())
                {

                    String emailCambioIBAN = SendMailChangeIBAN(_transazioni.Items.FirstOrDefault().CreditorName,_transazioni.Items.FirstOrDefault().CreditorIban, _VecchiaTransazione.CreditorIban);
                    if (!String.IsNullOrEmpty(emailCambioIBAN))
                    {

GestioneRimborsi.Web/Views/GestioneDisposizioni/List.cshtml
@model List<string>

@{
    ViewBag.Title = "Gestione disposizioni";

    Int64 temp = 0;

    if (!CurrentUser.HasPermissionOrIsPrivileged("gri.disposizioni"))
    {
        Response.Redirect(CommonUrls.BaseUrl);
    }
}

<div class="space-container">
    <div class="row paddingTop15">
        <div class="col-sm-12 space-container">
            <h2 class="mr-l">
                @CommonSnippets.IconLinkToHomepage
                /
                <i class="fa fa-list-ul"></i>
                <span class="text-after-icon">Modifica Disposizioni Bancarie</span>
            </h2>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12 space-container">
            <div class="col-sm-2">
                @Html.Partial("_leftMenu", "ModificaDisposizioniBancarie")
            </div>
            <div class="col-sm-10">
                @Html.Partial("~/views/GestioneDisposizioni/_schedaElencoModifiche.cshtml", temp)
                @Html.Partial("~/views/GestioneDisposizioni/_schedaModifiche.cshtml", new SepaCreditTransaction())
                @Html.Partial("~/views/Rimborsi/_confermaModificheModal.cshtml", "Confermare l'operazione di sbocco della disposizione selezionata?")

                <div class="gestione-disposizioni">
                    <div class="row border-bottom">
                        <div class="col-xs-12 col-md-3 col-sm-3 col-lg-3">
                            <p class="padTitle"></p><h4><label>Elenco Disposizioni</label></h4>
                        </div>
                        <div class="col-xs-12 col-md-9 col-sm-9 col-lg-9 border-left">
                            <h4><span id="t1"></span><label id="t2"></label><span id="t3"></span><label id="t4"></label></h4>
                            <h4><span id="t5"></span><label id="t6"></label></h4>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-xs-12 col-md-3 col-sm-3 col-lg-3">
                            @Html.Partial("~/views/shared/_modalWaiter.cshtml")

                            <div class="row">
                                <div class="col-xs-12 col-md-12 col-sm-12 col-lg-12 dropdown-selector">
                                    <div class="text-center" id="">
                                        <div class="btn-group" role="group">
                                            <select id="listaAutori" role="button" class="form-control selectCaret" onchange="loadInnerList();">
                                                <option value="-1" selected>Seleziona un utente  </option>
                                                @foreach (var x in Model)
                                                {
                                                    <option value="@x.ToString()">@x.ToString()</option>
                                                }
                                            </select>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-sm-12 disposizioni-container border-right">
                                    <ul id="headerList" class="list-group"></ul>
                                </div>
                            </div>
                        </div>

                        <div class="col-xs-12 col-md-9 col-sm-9 col-lg-9">
                            <div class="row">
                                <div class="col-sm-12" id="transactionTableContainer"></div>
                            </div>
                            <!--FOOTER-->
                            <div class="row">
                                <div class="col-sm-12"></div>
                            </div>
                        </div>

                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

<script>

    displayModalWaiter();
    var _url = '@Url.Action("SearchSepaHeader", "GestioneDisposizioni")';

    $.ajax({
        url: _url,
        type: 'POST',
        contentType: "application/json; charset=utf-8",
        data: JSON.stringify({
        }),
        success: function (result) {
            $("#headerList").html(result);
            hideModalWaiter();
        },
        error: function (request, status, error) {
            hideModalWaiter();
            notifyWarning(error);
        }
    });

    function setTransactionDataTable() {
        if ($.fn.dataTable.isDataTable('#grigliaTransazioni')) {
            _transactionTable = $('#grigliaTransazioni').DataTable();
        }
        else {
            _transactionTable = $('#grigliaTransazioni').DataTable({
                "pageLength": 7,
                columns: [
                null,
                null,
                null,
                null,
                { "orderable": false }
                ],
                order: [1, 'asc']
            });
        }
        $('[data-toggle="tooltip"]').tooltip();
    }
    $(function () {
        setTransactionDataTable();
    });

</script>

@section scripts {
    <script>

        $(".application-title").text("Gestione Rimborsi");

        function LoadInnerList(user) {
            displayModalWaiter();

            if (user != "" && user != null) {
                _innerListUrl = '@UrlFor.GestioneDisposizioni_InnerSepaList()' + user + '/';
            }
            else {
                _innerListUrl = '@UrlFor.GestioneDisposizioni_InnerSepaList()';
            }
            evaluateInnerListUrl(_innerListUrl, user);
        }

        $(function () {
            @{                
                //if (!RevoContext.IdentityManager.CurrentUser.HasPermission("GestioneRimborsi.GestionePermessi.ImpersonificaUtente"))
                if (!RevoContext.IdentityManager.CurrentUser.HasPermission("gri.disposizioni.scegliUtenti"))
                {
                    @:$('#rowFilter').hide();
        }
             }
        });

        function loadInnerList() {
            if ($("#listaAutori option:selected").val() != "-1") {
                LoadInnerList($("#listaAutori option:selected").val());
            }
            else {
                displayModalWaiter();
                evaluateInnerListUrl('@UrlFor.GestioneDisposizioni_SearchSepaHeader()', null);
            }
        }
        function evaluateInnerListUrl(url, user) {

            $.ajax({
                url: url,
                type: 'POST',
                contentType: "application/json; charset=utf-8",
                data: JSON.stringify({
                    Username: user
                }),
                success: function (result) {
                    $("#headerList").html(result);
                    if ($("#t2").text() != "" && $("#t2").text() != null) {
                        $("#" + $("#t2").text()).addClass("selected");
                    }
                    hideModalWaiter();
                },
                error: function (request, status, error) {
                    hideModalWaiter();
                    notifyWarning(error);
                }
            });
        }

    </script>
}

GestioneRimborsi.Web/Views/GestioneDisposizioni/_elencoDisposizioni.cshtml
@model ISubCollection<SepaHeader>

@{
    bool privileged = false;

    if (Model != null)
    {
        if (RevoRequest.CurrentUser.IsSuperUser() || RevoContext.IdentityManager.CurrentUser.IsPrivileged)
        {
            privileged = true;
        }
    }
}

@{
    foreach (SepaHeader _h in Model.Items)
    {
        <li class="item-disposizione list-group-item" id='@_h.ID' onclick="selectRow('@_h.ID', '@_h.Created.ToShortDateString()', '@_h.Autore')">
            <div class="row">
                <div class="col-sm-4">
                    <span>#: <strong>@_h.ID</strong></span>
                </div>
                <div class="col-sm-6 text-center no-padding">
                    <span>Del: <strong>@_h.Created.ToShortDateString()</strong></span>
                </div>
                <div class="col-sm-1 text-center fa-hover no-padding" onclick="downloadDisposizione('@_h.ID', '@_h.BloccatoDa');">
                    <a> <span class="fa fa-lg @(String.IsNullOrEmpty(_h.BloccatoDa)? "fa-download" : "fa-download") @(!String.IsNullOrEmpty(_h.BloccatoDa)? "disposizione-disabled":"")"></span> </a>
                </div>
                <div class="col-sm-1 text-center fa-hover no-padding" onclick="downloadCsvDisposizione('@_h.ID', '@_h.BloccatoDa');">
                    <a> <span class="fa fa-lg @(String.IsNullOrEmpty(_h.BloccatoDa) ? "fa-file-excel-o" : "fa-file-excel-o") @(!String.IsNullOrEmpty(_h.BloccatoDa)? "disposizione-disabled":"")"></span> </a>
                </div>
            </div>
            <div class="row row-margin">
                <div class="col-sm-10 border-top">
                    <span>Di: @_h.Autore</span>
                </div>

                <div class="col-sm-2 text-center fa-hover no-padding" onclick="bloccaDisposizione('@_h.ID', '@_h.BloccatoDa', '@_h.Autore')">
                    <a> <span id="locked" class="fa fa-lg @(String.IsNullOrEmpty(_h.BloccatoDa)? "fa-unlock-alt" : "fa-lock") @(!String.IsNullOrEmpty(_h.BloccatoDa)? "lock-disposizione":"")"></span> </a>
                </div>
            </div>
        </li>
    }
}

<script>

    $(".lock-disposizione").css({
        "color": "red",
    });

    @{
        if (!RevoContext.IdentityManager.CurrentUser.IsSuperUser())
        {
            @:$(".disposizione-disabled").css({ "color": "lightgray", });
                    @:$(".disposizione-disabled").attr("disabled", "disabled");
                }
    }

    function downloadDisposizione(id, bloccatoDa) {
        if (bloccatoDa == null || bloccatoDa == "") {
            window.location = '@UrlFor.DownloadDisposizioni'.replace("_id_", id);
        }
        @{
            if (RevoContext.IdentityManager.CurrentUser.IsSuperUser())
                {
                    @:window.location = '@UrlFor.DownloadDisposizioni'.replace("_id_", id);
                                }
        }
    }

    function downloadCsvDisposizione(id, bloccatoDa) {
        if (bloccatoDa == null || bloccatoDa == "") {
            window.location = '@UrlFor.DownloadCsvDisposizioni'.replace("_id_", id);
        }
        @{
            if (RevoContext.IdentityManager.CurrentUser.IsSuperUser())
            {
                @:window.location = '@UrlFor.DownloadCsvDisposizioni'.replace("_id_", id);
                    }
        }
    }

    function selectRow(id, creazione, autore) {
        displayModalWaiter();
        var _url = '@Url.Action("SearchSepaCreditTransaction", "GestioneDisposizioni", new { id = "_id_" })'.replace('_id_', encodeURIComponent(id));

        $(".list-group-item").removeClass("selected");
        $("#" + id).addClass("selected");

        $.ajax({
            url: _url,
            type: 'POST',
            contentType: "application/json; charset=utf-8",
            data: JSON.stringify({
                id: id
            }),
            success: function (result) {
                $("#transactionTableContainer").html(result);
                setTransactionDataTable();
                hideModalWaiter();

                $("#t1").text("Disposizione #: "); $("#t2").text("" + id);
                $("#t3").text(" creata in data "); $("#t4").text(creazione);
                $("#t5").text(" generata da: "); $("#t6").text(autore);
            },
            error: function (request, status, error) {
                hideModalWaiter();
                notifyWarning(error);
            }
        });
    }

    function bloccaDisposizione(id, autoreBlocco, utente) {

        if ('@privileged' == "True" && autoreBlocco != null && autoreBlocco != '') {
            $('#confermaModifiche').modal('show');

            $("#confMod").off().click(function () {
                bloccaSblocca(id, autoreBlocco);
            });
        }
        else { bloccaSblocca(id, autoreBlocco, utente); }
    }

    function bloccaSblocca(id, autoreBlocco, utente) {
        displayModalWaiter();
        var _url = '@Url.Action("BloccaDisposizione", "GestioneDisposizioni", new { id = "_id_", autoreBlocco = "_autore_" })'
                    .replace('_id_', encodeURIComponent(id).replace('_autore_', encodeURIComponent(autoreBlocco)));

        $.ajax({
            url: _url,
            type: 'POST',
            contentType: "application/json; charset=utf-8",
            data: JSON.stringify({
                id: id,
                autore: autoreBlocco
            }),
            success: function (result) {
                if (result != "") {
                    var user = "";
                    if ($("#listaAutori option:selected").val() != "-1") {
                        if ($("#listaAutori option:selected").val() != "" && $("#listaAutori option:selected").val() != null) {
                            _innerListUrl = '@UrlFor.GestioneDisposizioni_InnerSepaList()' + $("#listaAutori option:selected").val() + '/';
                            user = $("#listaAutori option:selected").val();
                        }
                        else {
                            _innerListUrl = '@UrlFor.GestioneDisposizioni_InnerSepaList()';
                        }
                        evaluateInnerListUrl(_innerListUrl, user);
                        $("#" + id).click();
                        $("#" + id).addClass("selected");
                    }
                    else {
                        _innerListUrl = '@UrlFor.GestioneDisposizioni_SearchSepaHeader()';
                        evaluateInnerListUrl(_innerListUrl, user);
                        $("#" + id).click();
                        $("#" + id).addClass("selected");
                    }
                }
                else { hideModalWaiter(); notifyWarning("Privilegi insufficienti per eseguire l'operazione."); }
            },
            error: function (request, status, error) {
                hideModalWaiter();
                notifyWarning(error);
            }
        });
    }

</script>

GestioneRimborsi.Web/Views/GestioneDisposizioni/_modificheIbanBeneficiario.cshtml
@model DisposizioneModificata

<div class="row">
    <div class="col-sm-12" id="container-modifica">
        <div class="row padding-top">
            <div class="col-sm-12">
                <label>IBAN</label>
            </div>
        </div>
        <div class="row item-border-bottom">
            @if (Model != null && Model.InternalId != null)
            {
                <div class="col-sm-6 no-padding-left">
                    <span class="@(Model.VecchioIBAN != Model.NuovoIBAN ? "strike-item" : "")">@Model.VecchioIBAN</span>
                </div>
                <div class="col-sm-6 no-padding-left">
                    <span>@(Model.NuovoIBAN != Model.VecchioIBAN ? Model.NuovoIBAN : "")</span>
                </div>
            }
        </div>
        <div class="row">
            <div class="col-sm-12">
                <label>Destinatario</label>
            </div>
        </div>
        <div class="row item-border-bottom">
            @if (Model != null && Model.InternalId != null)
            {
                <div class="col-sm-6 no-padding-left">
                    <span class="@(Model.VecchioBeneficiario != Model.NuovoBeneficiario ? "strike-item" : "")">@Model.VecchioBeneficiario</span>
                </div>
                <div class="col-sm-6 no-padding-left">
                    <span>@(Model.NuovoBeneficiario != Model.VecchioBeneficiario ? Model.NuovoBeneficiario : "")</span>
                </div>
            }
        </div>
    </div>
</div>

GestioneRimborsi.Web/Views/GestioneDisposizioni/_schedaElencoModifiche.cshtml
@model long

@{
    ILottoRimborsiService _lottoService = (ILottoRimborsiService)RevoContext.ServiceProvider.GetServiceFor<Rimborso>();

    ISubCollection<DisposizioneModificata> disposizioni = null;
    SepaCreditTransaction transaction = new SepaCreditTransaction();

    if (Model != null && Model != 0)
    {
        disposizioni = _lottoService.GetDisposizioniModificate(Model);
        transaction = _lottoService.GetTransactionByID(Model);
    }
}

<div id="schedaElencoModifiche">
    <div class="modal fade text-left" id="elencoModifiche" tabindex="-1" role="dialog" aria-labelledby="elencoModificheModalTitle" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span class="timesSize" aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="elencoModificheModalTitle">
                        <i class="fa fa-lg fa-list"></i>
                        <span class="text-after-icon">Elenco Modifiche</span>
                    </h4>
                </div>
                <div class="modal-body">
                    @if (Model != null && Model != 0 && disposizioni != null)
                    {
                        <div class="row">
                            <div class="col-sm-12">
                                <h5><span id="d1"></span><label id="d2"></label><span id="d3"></span><label id="d4"></label>
                                    <span id="d5"></span><label id="d6"></label></h5>
                                <h5><span id="datiCliente">Cliente <label>@transaction.CreditorName</label> (@transaction.CreditorTaxId)</span></h5>
                            </div>
                        </div>
                        <div class="row margine-sup">
                            <div class="col-sm-5">
                                <div class="row">
                                    <div class="col-sm-6 storico-header">
                                        <span class="">Autore</span>
                                    </div>
                                    <div class="col-sm-6 storico-header">
                                        <span class="">Data</span>
                                    </div>
                                </div>
                                <div class="row" id="storico-cambiamenti">
                                    <ul id="storicoCambiamentiList" class="list-group">
                                        @Html.Partial("~/Views/GestioneDisposizioni/_storicoCambiamenti.cshtml", disposizioni)
                                    </ul>
                                </div>
                            </div>
                            <div class="col-sm-7" id="containerCambiamenti">
                                @Html.Partial("~/Views/GestioneDisposizioni/_modificheIbanBeneficiario.cshtml", new DisposizioneModificata())
                            </div>
                        </div>
                    }
                </div>
                <div class="modal-footer mt-10">
                    <button type="button" data-dismiss="modal" class="btn btn-lg btn-function">
                        <span>Ok</span>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>

<script>

    $(function () {
        $("#d1").text("Disposizione "); $("#d2").text("#: " + $("#t2").text());
        $("#d3").text(" creata in data "); $("#d4").text($("#t4").text());
        $("#d5").text(" generata da: "); $("#d6").text($("#t6").text());        
    });   

</script>

GestioneRimborsi.Web/Views/GestioneDisposizioni/_storicoCambiamenti.cshtml
@model ISubCollection<DisposizioneModificata>

@{
    foreach (DisposizioneModificata _h in Model.Items)
    {
        <li class="item-storico list-group-item" id='@_h.InternalId' role="button" onclick="selectRow('@_h.InternalId')">
            <div class="row">
                <div class="col-sm-6">
                    <span>@_h.Autore</span>
                </div>
                <div class="col-sm-6">
                    <span>@_h.ModificatoIl.ToShortDateString()</span>
                </div>
            </div>
        </li>
    }
}

<script>

    function selectRow(internalId) {
        displayModalWaiter();
        var _url = '@Url.Action("GetStoricoModifica", "GestioneDisposizioni", new { internalId = "_id_" })'.replace('_id_', encodeURIComponent(internalId));

        $.ajax({
            url: _url,
            type: 'POST',
            contentType: "application/json; charset=utf-8",
            data: JSON.stringify({
                internalId: internalId
            }),
            success: function (result) {
                $("#containerCambiamenti").html(result);                
                hideModalWaiter();
            },
            error: function (request, status, error) {
                hideModalWaiter();
                notifyWarning(error);
            }
        });
    }

</script>