GestioneRimborsi.Web/Controllers/CapGroupingController.cs
using GruppoCap.Authentication.Core;
using GruppoCap.Core.Mvc;

namespace GestioneRimborsi.Web.Controllers
{
    public class CapGroupingController : BaseCapGroupingController
    {
        // CTOR
        public CapGroupingController(ICapGroupingService capGroupingService)
            : base(capGroupingService)
        {
            // EMPTY BY DEFAULT
        }
    }
}

GestioneRimborsi.Web/Views/CapGrouping/Delete.cshtml
@model CapGrouping
@{
    ViewBag.Title = Model.CapGroupingCode;
}

<div class="row">

    <div class="col-sm-12">

        <div class="row grid-title">
            <div class="col-sm-12">
                <h1>
                    <a href="@CommonUrls.Groupings"><i class="fa fa-fw fa-sitemap"></i></a>
                    / 
                    @ViewBag.Title
                </h1>
            </div>
        </div>

        <div class="row">

            <div class="col-sm-12">

                <div class="panel panel-info" style="margin-top:20px;">
                    <div class="panel-heading">
                        <h3 class="panel-title"><i class="fa fa-lg fa-info-circle"></i><span class="text-after-icon">Conferma la tua scelta...</span></h3>
                    </div>
                    <div class="panel-body">
                        <p>
                            Stai per cancellare il raggruppamento <strong>@Model.CapGroupingCode</strong>
                        </p>
                        <p>
                            <strong>Sei sicuro/a ???</strong> 
                        </p>
                        <div class="pull-right">
                            <a class="btn btn-default" href="@CommonUrls.Groupings">
                                <i class="fa fa-lg fa-arrow-circle-o-left"></i><span class="text-after-icon">Torna alla lista raggruppamenti</span>
                            </a>

                            @{
                                String _maybeDisabled = String.Empty;
                                if(Model.IsActive == false)
                                {
                                    _maybeDisabled = "disabled";
                                }
                            }

                            <a id="btnDelete" class="btn btn-danger @_maybeDisabled" href="javascript:void(0);" onclick="deleteCapGrouping('@Model.CapGroupingId');">
                                <i id="iconDelete" class="fa fa-lg fa-trash-o"></i><span class="text-after-icon">Elimina</span>
                            </a>
                        </div>
                    </div>
                </div>

            </div>

        </div>
        
    </div>

</div>

@section scripts {
    <script>
        $(function () {
            // INIT BOOTSTRAP TOOLTIP
            $('[data-toggle="tooltip"]').tooltip();
        });

        function deleteCapGrouping(capGroupingId) {
            
            startDeleteOperation('iconDelete');

            var _url;
            _url = '@Url.Action("Delete", "CapGrouping")';

            $.ajax({
                url: _url,
                type: 'POST',
                contentType: "application/json; charset=utf-8",
                data: JSON.stringify({
                    capGroupingId: capGroupingId
                }),
                success: function (result) {
                    var _resultStatus = result.status;
                    if (_resultStatus == 'success') {
                        notifySuccess('Il raggruppamento è stato cancellato correttamente!');
                    }
                    else {
                        notifyError(result.data.message);
                    }
                },
                error: function (request, status, error) {
                    notifyError('Qualcosa è andato storto durante la cancellazione del raggruppamento');
                }
            }).done(function () {
                endDeleteOperation('iconDelete');
                $("#btnDelete").addClass("disabled");
            }); // end ajax call
        } // deleteUser

    </script>
}

GestioneRimborsi.Web/Views/CapGrouping/Detail.cshtml
@model CapGrouping
@{
    ViewBag.Title = Model.CapGroupingCode;

    IUser _currentUser = RevoRequest.CurrentUser;
}

<div class="row">

    <div class="col-sm-12">

        <div class="row grid-title">
            <div class="col-sm-12">
                <h1>
                    <a href="@CommonUrls.Groupings"><i class="fa fa-fw fa-sitemap"></i></a>
                    /
                    @ViewBag.Title
                </h1>
            </div>
        </div>

        @Html.Partial("_trackedEntity", Model)

        <div class="row">

            <div class="col-sm-12">

                <form role="form" class="breath-on-top-8">

                    <div class="row">
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label for="txtCapGroupingId" class="control-label">Id</label>
                                <input type="text" class="form-control input-lg" id="txtCapGroupingId" value="@Model.CapGroupingId" disabled>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label for="txtCapGroupingCode" class="control-label">Codice</label>
                                <input type="text" class="form-control input-lg" id="txtCapGroupingCode" value="@Model.CapGroupingCode" disabled>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label for="txtDescription" class="control-label">Descrizione</label>
                                <input type="text" class="form-control" id="txtDescription" placeholder="inserisci il titolo / descrizione" value="@Model.Description">
                            </div>
                        </div>
                    </div>

                    <div class="well" style="margin-top: 20px;">
                        <div class="row">
                            <div class="col-sm-12">
                                <h3 class="well-title"><i class="fa fa-unlock-alt"></i><span class="text-after-icon">Abilitazioni</span></h3>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-3">
                                <div class="form-group" style="margin-bottom: 0px;">
                                    <label class="control-label">Attivazione dell'applicazione</label>
                                    @{
                                        String _isActiveDescription, _isActiveClass;
                                        String _applicationActiveText = "Raggruppamento attivo";
                                        String _applicationNotActiveText = "Raggruppamento NON attivo";

                                        _isActiveDescription = @Model.IsActive ? _applicationActiveText : _applicationNotActiveText;
                                        _isActiveClass = @Model.IsActive ? "text-primary" : "text-danger";
                                    }

                                    @Html.FontAwesomeCheckbox(
                                        "chkIsActive",
                                        Model.IsActive,
                                        _applicationActiveText,
                                        _applicationNotActiveText,
                                        "text-primary",
                                        "text-danger",
                                        _isActiveClass,
                                        _isActiveDescription
                                    )
                                </div>
                            </div>
                        </div>

                    </div>

                    <div class="row">
                        <div class="col-sm-6 col-sm-offset-6 text-right">
                            <a class="btn btn-lg btn-default" href="@CommonUrls.Groupings">
                                <i class="fa fa-lg fa-arrow-circle-o-left"></i><span class="text-after-icon">Torna alla lista raggrupamenti</span>
                            </a>
                            <a class="btn btn-lg btn-primary" href="javascript:void(0);" onclick="saveCapGrouping('@Model.CapGroupingId');">
                                <i id="iconSave" class="fa fa-lg fa-save"></i><span class="text-after-icon">Salva</span>
                            </a>
                        </div>
                    </div>

                </form>

            </div>

        </div>

    </div>

</div>

@section scripts {
<script>
    $(function () {
        // INIT BOOTSTRAP TOOLTIP
        $('[data-toggle="tooltip"]').tooltip();
    });

    function saveCapGrouping(capGroupingId) {
        var _url;
        var _id, _description, _isActive;
        
        startSaveOperation('iconSave');

        _url = '@Url.Action("Update", "CapGrouping")';
        _id = capGroupingId;

        _description = $("#txtDescription").val();
        _isActive = isFontAwesomeChecked('#chkIsActive');
        
        $.ajax({
            url: _url,
            type: 'POST',
            contentType: "application/json; charset=utf-8",
            data: JSON.stringify({
                capGroupingId: _id,
                description: _description,
                isActive: _isActive
            }),
            success: function (result) {
                var _resultStatus = result.status;
                if (_resultStatus == 'success') {
                    notifySuccess(result.data.message);
                }
                else {
                    notifyError(result.data.message);
                }
            },
            error: function (request, status, error) {
                notifyError('Qualcosa è andato storto durante il salvataggio dei dati');
            }
        }).done(function () {
            endSaveOperation('iconSave');
        }); // end ajax call
    } // saveUser
</script>
}

GestioneRimborsi.Web/Views/CapGrouping/List.cshtml
@model ISubCollection<CapGrouping>

<div class="row">

    <div class="col-sm-12">

        <div class="row grid-title">
            <div class="col-sm-6">
                <h1>
                    Elenco Raggruppamenti
                </h1>
            </div>
            <div class="col-sm-6 text-right">
                <button type="button" class="btn btn-default title-bar-entity-button" data-toggle="modal" data-target="#createCapGroupingModal">
                    <i class="fa fa-lg fa-desktop"></i>
                    <span class="text-after-icon">Crea nuovo raggruppamento</span>
                </button>
            </div>
        </div>

        <div class="row">

            <div class="col-sm-12" id="capGroupingTableContainer">

                @Html.Partial("_list", Model)

            </div>

        </div>
        
    </div>

    @Html.Partial("_create")

</div>

@section scripts {
<script>

    var _capGroupingTable;

    function setCapGroupingDataTable() {
        if ($.fn.dataTable.isDataTable('#gridCapGrouping')) {
            _capGroupingTable = $('#gridCapGrouping').DataTable();
        }
        else {
            _capGroupingTable = $('#gridCapGrouping').DataTable({
                columns: [
                { "orderable": false, className: "info-column" }, // ICONs
                null,
                null,
                { "orderable": false, className: "command-column" } // COMMANDs
                ],
                order: [1, 'asc']
            });
        }

        // INIT BOOTSTRAP TOOLTIP
        $('[data-toggle="tooltip"]').tooltip();
    }

    $(function () {
        // INIT ENHANCED DATAGRID (_list)
        setCapGroupingDataTable();
    });

</script>
}

GestioneRimborsi.Web/Views/CapGrouping/_create.cshtml
<div class="modal fade" id="createCapGroupingModal" tabindex="-1" role="dialog" aria-labelledby="createCapGroupingModalTitle" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="createCapGroupingModalTitle">
                    <i class="fa fa-lg fa-desktop"></i>
                    <span class="text-after-icon">Nuovo raggruppamento</span>
                </h4>
            </div>
            <div class="modal-body">
                
                <div class="row">

                    <div class="col-sm-12">

                        <form role="form" class="breath-on-top-8">

                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label for="txtCapGroupingCode" class="control-label">Cap Grouping Code</label>
                                        <input type="text" class="form-control input-lg" id="txtCapGroupingCode" placeholder="inserisci il codice">
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label for="txtDescription" class="control-label">Descrizione</label>
                                        <input type="text" class="form-control input-lg" id="txtDescription" placeholder="inserisci il titolo / descrizione">
                                    </div>
                                </div>
                            </div>

                        </form>

                    </div>

                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-lg btn-default" data-dismiss="modal">
                    <i class="fa fa-lg fa-arrow-circle-o-left"></i><span class="text-after-icon">Torna alla lista raggruppamenti</span>
                </button>
                <a id="btnCreateCapGrouping" class="btn btn-lg btn-primary" href="javascript:void(0);" onclick="createCapGrouping();">
                    <i id="iconSave" class="fa fa-lg fa-save"></i><span class="text-after-icon">Salva</span>
                </a>
            </div>
        </div>
    </div>
</div>

<script>

    function createCapGrouping() {

        var _url;
        var _code, _description;

        startSaveOperation('iconSave');

        _url = '@Url.Action("Create", "CapGrouping")';

        _code = $("#txtCapGroupingCode").val();
        _description = $("#txtDescription").val();
        
        $.ajax({
            url: _url,
            type: 'POST',
            contentType: "application/json; charset=utf-8",
            data: JSON.stringify({
                capGroupingCode: _code,
                description: _description
            }),
            success: function (result) {
                var _resultStatus = result.status;
                if (_resultStatus == 'success') {
                    notifySuccess(result.data.message);
                }
                else {
                    notifyError(result.data.message);
                }
            },
            error: function (request, status, error) {
                notifyError('Qualcosa è andato storto durante il salvataggio dei dati');
            }
        }).done(function () {
            endSaveOperation('iconSave');
            $('#createCapGroupingModal').modal('hide');
        }); // end ajax call
    } // saveUser
</script>

GestioneRimborsi.Web/Views/CapGrouping/_list.cshtml
@model ISubCollection<CapGrouping>

<table id="gridCapGrouping" class="table table-condensed table-hover">
    <thead>
        <tr>
            <th></th>
            <th>Codice</th>
            <th>Descrizione</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @{
            foreach (CapGrouping _g in Model.Items)
            {
                String _trClass = String.Empty;
                String _trIcon = String.Empty;

                if (_g.IsActive == false)
                {
                    _trClass += "danger";
                    _trIcon += CommonSnippets.IsNotActive;
                }

                <tr onclick="loadCapGroupingDetail('@_g.CapGroupingId');" class="@_trClass">
                    <td>@Html.Raw(_trIcon)</td>
                    <td>@_g.CapGroupingCode</td>
                    <td>@_g.Description.Truncate(80, true)</td>
                    <td>
                        @{
                            if (_g.IsActive)
                            {
                                <a class="deleteButtonInList" href="javascript:void(0);" onclick="loadCapGroupingDeletePreview('@_g.CapGroupingId');"><i class="fa fa-lg fa-fw fa-trash"></i></a>
                            }
                        }
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

<script>
    $('.deleteButtonInList').click(function (event) {
        event.stopPropagation();
    });

    function loadCapGroupingDeletePreview(capGroupingId) {
        var _url = "@CommonUrls.CapGroupingDelete("_capGroupingId_")".replace('_capGroupingId_', capGroupingId);
        window.location.href = _url;
    }

    function loadCapGroupingDetail(capGroupingId) {
        var _url = "@CommonUrls.CapGroupingDetail("_capGroupingId_")".replace('_capGroupingId_', capGroupingId);
        window.location.href = _url;
    }
</script>