GestioneRimborsi.Web/Controllers/LottoRimborsiController.cs
using GruppoCap.Core;
using GruppoCap.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using GruppoCap.Core.Data;
using GestioneRimborsi.Core;
using GruppoCap;
using System.Xml;
using System.Text;
using System.IO;
using SepaManager.Base;
using System.Xml.Linq;
namespace GestioneRimborsi.Web.Controllers
{
    public class LottoRimborsiController : RevoController
    {

        private ILottoRimborsiService _lottorimborsiService = null;
        // CTOR
        public LottoRimborsiController(ILottoRimborsiService lottorimborsiService, ILogger log)
        {
            _lottorimborsiService = lottorimborsiService;
            _log = log;
        }

        ILogger _log;

        public ActionResult List()
        {
            return View(_lottorimborsiService.UsersOfRimborsi());
        }
        public ActionResult InnerList(string UserName)
        {
            try
            {
                if (string.IsNullOrEmpty(UserName))
                    return PartialMessage(HtmlSnippets.Alert.Info("Selezionare un utente e premere Cerca per visualizzare i rimborsi..."));

                ISubCollection<Rimborso> _rimborsi = _lottorimborsiService.LottoRimborsiByUserName(UserName);

                if (_rimborsi.Items.HasValues() == false)
                {
                    return PartialMessage(
                        HtmlSnippets.Alert.Warning(string.Format("Non ho trovato rimborsi per l'utente {0}", UserName))
                    );
                }
                ViewData.Add("UserName", UserName);
                return PartialView("_list", _rimborsi);
            }
            catch (Exception ex)
            {
                if (RevoContext.IdentityManager.CurrentUser.IsPrivileged)
                    return PartialMessage(HtmlSnippets.Alert.Error(string.Format("Errore durante la lettura dei rimborsi...{0}{1}", Environment.NewLine, ex)));
                else
                    return PartialMessage(HtmlSnippets.Alert.Error("Errore durante la lettura dei rimborsi..."));
            }
        }
        [HttpPost]
        public JsonResult GeneraFileRimborsi(string UserName, DateTime DataValuta)
        {
            var proxy = new BankXMLManager.BankXMLServiceClient();
            var id = proxy.CreateXml(string.Format("{0}_{1}", UserName, DateTime.Now.ToString("yyyyMMddHHmmssms")), UserName, RevoRequest.CurrentUser.UserId);

            if (id <= 0)
                return Json(new { status = "failed", data = new { message = "Errore durante la creazione del file xml..." } });

            try
            {

                BankXMLOutput _XmlOutput = proxy.GetXmlDocument(id);

                IUpdateOperationResult setRimborsiUpdated = null;

                setRimborsiUpdated = _lottorimborsiService.Update(UserName, _XmlOutput.FileName, RevoContext.IdentityManager.CurrentUsername, DataValuta);

                if (!setRimborsiUpdated.GenericMeaning)
                    return Json(new { status = "failed", data = new { message = string.Format("Errore durante l'aggiornamento dei rimborsi...{0}{1}", Environment.NewLine, setRimborsiUpdated.Description) } });
                else _log.Append("Gestione disposizioni -> Generato file xml (" + _XmlOutput.FileName + ") -> Aggiornamento data rimborso: ", LogLevel.Info, null, "La data rimborso nella tabella GIN_INDENNIZZI_CDS è stata aggiornata al " + DataValuta.ToShortDateString() + " dall'utente " + RevoContext.IdentityManager.CurrentUsername);

            }
            catch (Exception ex)
            {
                return Json(new { status = "failed", data = new { message = string.Format("Errore durante l'aggiornamento dei rimborsi...{0}{1}", Environment.NewLine, ex) } });
            }
            
            return Json(new { status = "success", data = new { id = id } });

        }
        public FileResult DownloadFileRimborsi(long id)
        {
            var proxy = new BankXMLManager.BankXMLServiceClient();
            if (id <= 0)
                throw new ApplicationException("Errore durante la creazione del file xml...");
            BankXMLOutput _XmlOutput = proxy.GetXmlDocument(id);
            System.Xml.Linq.XElement _xmlFile = XElement.Parse(_XmlOutput.XmlDocument.OuterXml);
            //StringBuilder fs = new StringBuilder();
            StringWriterWithEncoding fs = new StringWriterWithEncoding(Encoding.UTF8);

            using (XmlWriter xmlW = XmlWriter.Create(fs, new XmlWriterSettings() { OmitXmlDeclaration = false, ConformanceLevel = ConformanceLevel.Document, Encoding = Encoding.UTF8 }))
            {
                _xmlFile.WriteTo(xmlW);
                xmlW.Flush();
            }
            Console.WriteLine("Task Executed");
            byte[] bytes = Encoding.UTF8.GetBytes(fs.ToString());
            HttpContext.Response.Headers.Add("Content-Disposition", string.Format("attachment; filename=\"{0}\"", (_XmlOutput.FileName ?? string.Format("{0}_{1}", id, DateTime.Now.ToString("yyyyMMddHHmmssms"))).EnsureEndsWith(".xml")));

            //Aggiorno campo data_valuta


            return File(bytes, "text/xml");
        }

        public ActionResult SetDataValuta(DateTime DataValuta, String UserName)
        {
            if (string.IsNullOrEmpty(UserName))
                return PartialMessage(HtmlSnippets.Alert.Info("Nessun utente selezionato"));

            ISubCollection<Rimborso> rimborsi = _lottorimborsiService.LottoRimborsiByUserName(UserName);
            String result = _lottorimborsiService.SetDataValuta(DataValuta, rimborsi);
            return new EmptyResult();
        }

        public ActionResult ModificaDisposizioniBancarie()
        {
            return View(_lottorimborsiService.UsersOfRimborsi());
        }

        [Authorize]
        public ActionResult SearchSepaHeader()
        {
            try
            {
                ISubCollection<SepaHeader> _elencoDisposizioni = _lottorimborsiService.GetSepaHeader();
                return PartialView("~/Views/LottoRimborsi/_elencoDisposizioni.cshtml", _elencoDisposizioni);
            }
            catch (Exception ex)
            {
                if (RevoContext.IdentityManager.CurrentUser.IsPrivileged)
                    return PartialMessage(HtmlSnippets.Alert.Error(string.Format("Errore durante la ricerca...{0}{1}", Environment.NewLine, ex)));
                else
                    return PartialMessage(HtmlSnippets.Alert.Error("Errore durante la ricerca..."));
            }
        }
    }



    internal sealed class StringWriterWithEncoding : StringWriter
    {
        private readonly Encoding encoding;

        public StringWriterWithEncoding(Encoding encoding)
        {
            this.encoding = encoding;
        }

        public override Encoding Encoding
        {
            get { return encoding; }
        }
    }
}

GestioneRimborsi.Web/Views/LottoRimborsi/List.cshtml
@model List<string>

@{
    ViewBag.Title = "Gestione Rimborsi";

    if (!CurrentUser.HasPermissionOrIsPrivileged("gri.disposizioni"))
    {
        Response.Redirect(CommonUrls.BaseUrl);
    }
}

<div class="space-container">
    <div class="row paddingTop15">
        <div class="col-sm-12 space-container">
            <h2 class="mr-l">
                @CommonSnippets.IconLinkToHomepage
                /
                <i class="fa fa-credit-card"></i>
                <span class="text-after-icon">Gestione disposizioni</span>
            </h2>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12 space-container">
            <div class="col-sm-2">
                @Html.Partial("_leftMenu", "GestioneDisposizioni")
            </div>
            <div class="col-sm-10">
                <div class="panel">
                    <div class="row" id="panelLottoRimborsi">
                        @Html.Partial("~/views/shared/_modalWaiter.cshtml")

                        <div class="text-center" id="rowFilter">
                            <div class="btn-group mt-10" role="group">
                                <div class="btn-group" role="group">
                                    @{
                                        var _caret = "";
                                        var _caretVal = "";
                                        //if (RevoContext.IdentityManager.CurrentUser.HasPermission("GestioneRimborsi.GestionePermessi.ImpersonificaUtente"))
                                        if (!RevoContext.IdentityManager.CurrentUser.HasPermission("gri.disposizioni.scegliUtenti"))
                                        {
                                            if (Model.Contains(RevoRequest.CurrentUser.UserId))
                                            {
                                                _caret = RevoRequest.CurrentUser.UserId;
                                                _caretVal = _caret;
                                            }
                                            else
                                            {
                                                _caret = "Seleziona un utente  ";
                                                _caretVal = "";
                                            }
                                        }
                                        else
                                        {
                                            _caret = RevoRequest.CurrentUser.UserId;
                                            _caretVal = _caret;
                                        }
                                    }
                                    <button type="button" class="btn btn-default dropdown-toggle" id="ddlUsers"
                                            data-toggle="dropdown" value="@_caretVal">
                                        @_caret
                                        <span class="caret"></span>
                                    </button>
                                    <ul class="dropdown-menu" id="ddlUsers-list">
                                        @foreach (var x in Model)
                                        {
                                            <li><a href="#">@x.ToString()</a></li>
                                        }
                                    </ul>
                                </div>
                                <a class="btn btn-default" id="btnSearch" onclick="LoadInnerList()">
                                    <i class="fa fa-lg fa-search"></i>
                                    <span class="text-after-icon">Cerca</span>
                                </a>
                            </div>
                        </div>
                        <div class="breath-on-top-20 col-sm-12 container-information" id="rimborsiTableContainer"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



@section scripts {

    <script>

        $(".application-title").text("Gestione Rimborsi");

        function LoadInnerList() {
            displayModalWaiter();

            if ($('#ddlUsers').attr('value') != '') {
                _innerListUrl = '@UrlFor.LottoRimborsi_InnerList()' + $('#ddlUsers').attr('value') + '/';
            }
            else {
                _innerListUrl = '@UrlFor.LottoRimborsi_InnerList()';
            }
            $("#rimborsiTableContainer").load(_innerListUrl, function () {
                hideModalWaiter();
            });
        }

        $(function () {
            @{
                //if (!RevoContext.IdentityManager.CurrentUser.HasPermission("GestioneRimborsi.GestionePermessi.ImpersonificaUtente"))
                if (!RevoContext.IdentityManager.CurrentUser.HasPermission("gri.disposizioni.scegliUtenti"))
                {
                    @:$('#rowFilter').hide();
                                                                                                                                                                                }
             }
            $('#btnSearch').addClass('disabled');
            LoadInnerList()
        });

        $('#ddlUsers-list a').on('click', function () {
            $('#ddlUsers').html($(this).html() + '   <span class="caret"></span>');
            $('#ddlUsers').attr('value', $(this).html());
            $('#btnSearch').removeClass('disabled');
        })

    </script>
}

GestioneRimborsi.Web/Views/LottoRimborsi/_list.cshtml
@using GruppoCap
@using GruppoCap.Core.Data
@using GestioneRimborsi.Core

@model ISubCollection<Rimborso>

@{
    IUser _currentUser = RevoRequest.CurrentUser;
}

@*@if (!RevoContext.IdentityManager.CurrentUser.HasPermission("GestioneRimborsi.GestionePermessi.ImpersonificaUtente"))*@
@if (!RevoContext.IdentityManager.CurrentUser.HasPermission("gri.disposizioni.scegliUtenti"))
{
    <div class="info-panel">
        <i class="fa fa-lg fa-user"></i><span class="text-after-icon">Elenco rimborsi dell'utente @ViewData["UserName"]</span>
    </div>
}
<table id="gridLottoRimborsi" class="table table-condensed table-hover">
    <thead>
        <tr>
            <th class="text-left" width="15%">Codice Cliente</th>
            <th class="text-left" width="15%">ID Rimborso</th>
            <th class="text-left" width="23%">IBAN</th>
            <th class="text-left" width="23%">Banca di appoggio</th>
            <th class="text-center" width="7%">ABI</th>
            <th class="text-center" width="7%">CAB</th>
            <th class="text-right" width="10%">Importo</th>
        </tr>
    </thead>
    <tbody>
        @{
            foreach (Rimborso _r in Model.Items)
            {
                <tr>
                    <td class="text-left">@_r.CodiceClienteDestinatario</td>
                    <td class="text-left">@_r.IdRimborso</td>
                    <td class="text-left">@_r.IbanDestinatario</td>
                    <td class="text-left">@_r.DescrizioneBancaOrdinante</td>
                    <td class="text-center">@_r.AbiOrdinante</td>
                    <td class="text-center">@_r.CabOrdinante</td>
                    <td class="text-right"> @Html.DisplayFor(model => _r.TotaleEuro)</td>
                </tr>
            }
        }
    </tbody>
</table>
<table class="table table-condensed table-hover">
    <tr>
        <td class="colorTransparent" colspan="7"><p></p></td>
    </tr>
    <tr>
        <td colspan="6"><strong>Numero Disposizioni</strong></td>
        <td class="text-right"><strong>@Model.Items.Count()</strong></td>
    </tr>
    <tr>
        <td colspan="5"><strong>Totale Disposizioni</strong></td>
        <td class="text-right" colspan="2"><strong>@String.Format("{0:C}", Model.Items.Sum(s => s.TotaleEuro))</strong></td>
    </tr>
    <tr>
        <td colspan="4"><strong>Data Valuta</strong></td>
        <td colspan="5">
            <div id="calendarDiv2" class="input-group input-append date pull-right">
                <input class="form-control" data-format="dd/MM/yyyy" type="text" id="calendar" name="calendar" value='@DateTime.Now.ToShortDateString()' />
                <span class="input-group-btn add-on">
                    <button class="btn btn-default h-btn-new" type="button">
                        <i class="fa fa-lg fa-calendar"></i>
                    </button>
                </span>
            </div>

        </td>

    </tr>
</table>

<div class="pull-right">
    <a id="btnGeneraFileRimborsi" class="btn btn-function title-bar-entity-button pull-right" href=" javascript:void(0);" onclick="DownloadFileRimborsi()">
        <i class=" fa fa-lg fa-file-text-o" id="iconGeneraFile"></i>
        <span class="text-after-icon">Genera File Rimborsi</span>
    </a>
</div>

<script>

    $(function () {
        $('#calendarDiv2').datetimepicker();
        jQuery.extend(jQuery.fn.dataTableExt.oSort, {
            "currency-pre": function (a) {
                a = (a === "-") ? 0 : a.replace(/[^\d\-\,]/g, "").replace(/,/, ".");
                return parseFloat(a);
            },

            "currency-asc": function (a, b) {
                return ((a < b) ? -1 : ((a > b) ? 1 : 0));
            },

            "currency-desc": function (a, b) {
                return ((a < b) ? 1 : ((a > b) ? -1 : 0));
            }
        });
        jQuery.extend(jQuery.fn.dataTableExt.oSort, {
            "numeric-comma-pre": function (a) {
                var x = (a == "-") ? 0 : a.replace(/,/, ".");
                return parseFloat(x);
            },

            "numeric-comma-asc": function (a, b) {
                return ((a < b) ? -1 : ((a > b) ? 1 : 0));
            },

            "numeric-comma-desc": function (a, b) {
                return ((a < b) ? 1 : ((a > b) ? -1 : 0));
            }
        });

        $('#gridLottoRimborsi').DataTable({
            columnDefs: [
              { type: 'currency', targets: 6 }
            ]
        });
    });

    function DownloadFileRimborsi() {
        if ($("#calendar").val() == '') {
            notifyWarning("Nessuna data valuta inserita..."); return false;
        }
        var _url = '@UrlFor.GeneraFileRimborsi';

        startGenericOperation('iconGeneraFile', 'file-text-o');
        displayModalWaiter();
        @if (string.IsNullOrEmpty(ViewData["UserName"].ToString())) {
            @:notifyError('Non è stato trovato nessun rimborso!');
                    @:return;
                }
        if (_url == '') {
            notifyError('Attenzione, url per il download del file non valido!');
            endGenericOperation('iconSend', 'send');
            return;
        }
        $.ajax({
            url: _url,
            type: 'POST',
            contentType: "application/json; charset=utf-8",
            data: JSON.stringify({
                UserName: '@ViewData["UserName"].ToString()',
                DataValuta: $("#calendar").val()
            }),
            success: function (result) {
                var _resultStatus = result.status;
                if (_resultStatus == 'success') {
                    hideModalWaiter();
                    window.location = '@UrlFor.DownloadFileRimborsi'.replace("_id_", result.data.id);
                    $("#btnGeneraFileRimborsi").addClass("disabled");
                }
                else {
                    notifyError(result.data.message);
                }
            },
            error: function (request, status, error) {
                notifyError('Qualcosa è andato storto durante la generazione del file: ' + error);
            }
        }).done(function () {
            hideModalWaiter();
            endGenericOperation('iconGeneraFile', 'file-text-o');
        });
    }

    function setDataValuta() {

        var _url = '@Url.Action("SetDataValuta", "LottoRimborsi")';

        $.ajax({
            url: _url,
            type: 'POST',
            contentType: "application/json; charset=utf-8",
            data: JSON.stringify({
                DataValuta: $("#calendar").val(),
                Username: '@ViewData["UserName"].ToString()',
            }),
            success: function (result) {
                var _resultStatus = result.status;
                if (_resultStatus == 'success') {
                }
                else {
                    notifyError(result.data.message);
                }
            },
            error: function (request, status, error) {
                notifyError('Qualcosa è andato storto durante il salvataggio della data valuta: ' + error);
            }
        });
    }

</script>